version: '1.0'
stages:
  - 'clone'
  - 'install'
  - 'checks'
  - 'deploy'

steps:
  clone:
    title: 'Cloning repository'
    type: 'git-clone'
    repo: 'HedvigInsurance/hedgehog'
    revision: '${{CF_BRANCH}}'
    git: 'github'
    stage: 'clone'

  build_dependency_container:
    title: 'Building Docker image'
    type: 'build'
    image_name: 'hedviginsurance/hedgehog'
    disable_push: true
    working_directory: '${{clone}}'
    dockerfile: .ci/Dockerfile
    stage: 'install'
    when:
      branch:
        ignore:
          - master

  install_deps:
    title: 'Installing dependencies'
    type: 'freestyle'
    image: '${{build_dependency_container}}'
    working_directory: '${{clone}}'
    commands:
      - yarn
      - yarn graphql:gen
    stage: 'install'
    when:
      branch:
        ignore:
          - master

  checks:
    title: 'Running checks'
    type: 'parallel'
    steps:
      - title: 'Linting'
        type: 'freestyle'
        image: '${{build_dependency_container}}'
        working_directory: '${{clone}}'
        commands:
          - yarn lint
      - title: 'Testing'
        type: 'freestyle'
        image: '${{build_dependency_container}}'
        working_directory: '${{clone}}'
        commands:
          - yarn test
      - title: 'Typecheck'
        type: 'freestyle'
        image: '${{build_dependency_container}}'
        working_directory: '${{clone}}'
        commands:
          - yarn typecheck
    stage: 'checks'
    when:
      branch:
        ignore:
          - master

  build_client:
    title: 'Building client'
    type: 'freestyle'
    image: '${{build_dependency_container}}'
    working_directory: '${{clone}}'
    commands:
      - yarn build
    stage: 'checks'
    when:
      branch:
        ignore:
          - master

  deploy_to_heroku:
    title: 'Deploying to Heroku'
    stage: 'deploy'
    type: 'heroku-deployer'
    arguments:
      APP_NAME: $APP_NAME
      EMAIL: $EMAIL
      API_TOKEN: $API_TOKEN
    when:
      branch:
        only:
          - master
