export const ADD_MESSAGE = 'ADD_MESSAGE'
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED'
export const ERROR_RECEIVED = 'ERROR_RECEIVED'
export const CLEAR_MESSAGES_LIST = 'CLEAR_MESSAGES_LIST'
export const SET_ACTIVE_CONNECTION = 'SET_ACTIVE_CONNECTION'

export const MEMBER_REQUESTING = 'MEMBER_REQUESTING'
export const MEMBER_REQUEST_SUCCESS = 'MEMBER_REQUEST_SUCCESS'
export const MEMBER_REQUEST_ERROR = 'MEMBER_REQUEST_ERROR'

export const MEMBERS_REQUESTING = 'MEMBERS_REQUESTING'
export const MEMBERS_REQUEST_SUCCESS = 'MEMBERS_REQUEST_SUCCESS'
export const MEMBERS_ERROR = 'MEMBERS_ERROR'

export const MEMBER_SEARCH_REQUESTING = 'MEMBER_SEARCH_REQUESTING'
export const MEMBERS_SEARCH_SUCCESS = 'MEMBERS_SEARCH_SUCCESS'

export const NEW_MESSAGES_RECEIVED = 'NEW_MESSAGES_RECEIVED'

export const SET_MEMBER_FILTER = 'SET_MEMBER_FILTER'

export const SORT_MEMBERS_LIST = 'SORT_MEMBERS_LIST'

export const SEND_CERTIFICATE = 'SEND_CERTIFICATE'
export const SEND_CERTIFICATE_SUCCESS = 'SEND_CERTIFICATE_SUCCESS'
export const SEND_CERTIFICATE_ERROR = 'SEND_CERTIFICATE_ERROR'

export const EDIT_MEMBER_DETAILS = 'EDIT_MEMBER_DETAILS'
export const EDIT_MEMBER_DETAILS_SUCCESS = 'EDIT_MEMBER_DETAILS_SUCCESS'

export const SET_FRAUDULENT_STATUS = 'SET_FRAUDULENT_STATUS'
export const SET_FRAUDULENT_STATUS_SUCCESS = 'SET_FRAUDULENT_STATUS_SUCCESS'
