export const MEMBERS_REQUESTING = 'MEMBERS_REQUESTING'
export const MEMBERS_REQUEST_SUCCESS = 'MEMBERS_REQUEST_SUCCESS'
export const MEMBERS_ERROR = 'MEMBERS_ERROR'

export const MEMBER_SEARCH_REQUESTING = 'MEMBER_SEARCH_REQUESTING'
export const MEMBERS_SEARCH_SUCCESS = 'MEMBERS_SEARCH_SUCCESS'

export const SET_MEMBER_FILTER = 'SET_MEMBER_FILTER'

export const SORT_MEMBERS_LIST = 'SORT_MEMBERS_LIST'

export const SET_FRAUDULENT_STATUS = 'SET_FRAUDULENT_STATUS'
export const SET_FRAUDULENT_STATUS_SUCCESS = 'SET_FRAUDULENT_STATUS_SUCCESS'
