name: CI & CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: 'Build and Test'
    runs-on: ubuntu-latest

    steps:
      - name: SETUP - Checkout repo
        uses: actions/checkout@v2

      - name: SETUP - Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0

      - name: Build & Test
        run:  |
          npm install
          npm run graphql:gen
          npm run lint
          npm run test
          npm run typecheck
          npm run build
